export const switchButton = document.querySelector('.pokedex__light-switch')
export const searchText = document.querySelector('.pokedex__search-text')
export const searchButton = document.querySelector('.pokedex__search-button')
export const pokeImg = document.querySelector('.pokemon-image')
export const messsageError = document.querySelector('.error')
export const buttonsId = document.querySelectorAll('.grid-id__item')

export const containerInfos = document.querySelector('.pokedex__pokemon-infos')
export const fieldPokemonId = document.querySelector('.field-pokemon-id')
export const fieldPokemonName = document.querySelector('.field-pokemon-name')
export const fieldPokemonAbility = document.querySelector('.field-pokemon-ability')
export const fieldPokemonType = document.querySelector('.field-pokemon-type')
export const buttonElarge = document.querySelector('.button-elarge')
export const buttonDecrease = document.querySelector('.button-decrease')